### ISSUE TITLE
npm run build 打包失败

### ISSUE THREAD

**Issue by Johnson-Rod** [sanmmm/MusicRadio#1]
> @ build /root/MusicRadio/frontend
> umi build

✖ Webpack
  Compiled with some errors in 1.74m

 ERROR  Failed to compile with 3 errors                                     4:38:12 ├F10: PM┤

This dependency was not found:

* config/settings in ./src/layouts/index.tsx, ./src/layouts/header.tsx and 1 other

To install it, you can run: npm install --save config/settings
Child
    
    ERROR in ./src/layouts/index.tsx
    Module not found: Error: Can't resolve 'config/settings' in '/root/MusicRadio/frontend/src/layouts'
     @ ./src/layouts/index.tsx 10:0-39 37:71-79
     @ ./src/.umi-production/core/routes.ts
     @ ./src/.umi-production/umi.ts
     @ multi ./node_modules/@umijs/bundler-webpack/lib/getConfig/runtimePublicPathEntry.js ./src/.umi-production/umi.ts
    
    ERROR in ./src/layouts/header.tsx
    Module not found: Error: Can't resolve 'config/settings' in '/root/MusicRadio/frontend/src/layouts'
     @ ./src/layouts/header.tsx 31:0-39 128:11-19 240:5-13 240:26-34 266:113-121 271:30-38
     @ ./src/layouts/index.tsx
     @ ./src/.umi-production/core/routes.ts
     @ ./src/.umi-production/umi.ts
     @ multi ./node_modules/@umijs/bundler-webpack/lib/getConfig/runtimePublicPathEntry.js ./src/.umi-production/umi.ts
    
    ERROR in ./src/services/socket.ts
    Module not found: Error: Can't resolve 'config/settings' in '/root/MusicRadio/frontend/src/services'
     @ ./src/services/socket.ts 2:0-39 14:51-59
     @ ./src/models/playList.ts
     @ ./src/.umi-production/plugin-dva/dva.ts
     @ ./src/.umi-production/plugin-dva/runtime.tsx
     @ ./src/.umi-production/core/plugin.ts
     @ ./src/.umi-production/umi.ts
     @ multi ./node_modules/@umijs/bundler-webpack/lib/getConfig/runtimePublicPathEntry.js ./src/.umi-production/umi.ts
    
    ERROR in /root/MusicRadio/frontend/src/components/roomVisualization/index.tsx
    [tsl] ERROR in /root/MusicRadio/frontend/src/components/roomVisualization/index.tsx(315,23)
          TS2769: No overload matches this call.
      Overload 1 of 2, '(props: Readonly<ReactEchartsCorePropsTypes>): ReactEchartsCore', gave the following error.
        Type '{ title: {}; visualMap: ({ type: string; splitNumber: number; min: number; max: number; dimension: number; seriesIndex: number; showLabel: boolean; show: boolean; inRange: { color: string[]; symbolSize: number[]; }; outOfRange: { ...; }; } | { ...; })[]; geo: { ...; }; series: ({ ...; } | { ...; })[]; }' is not assignable to type 'EChartOption<Series>'.
          Types of property 'visualMap' are incompatible.
            Type '({ type: string; splitNumber: number; min: number; max: number; dimension: number; seriesIndex: number; showLabel: boolean; show: boolean; inRange: { color: string[]; symbolSize: number[]; }; outOfRange: { ...; }; } | { ...; })[]' is not assignable to type 'VisualMap[]'.
              Type '{ type: string; splitNumber: number; min: number; max: number; dimension: number; seriesIndex: number; showLabel: boolean; show: boolean; inRange: { color: string[]; symbolSize: number[]; }; outOfRange: { ...; }; } | { ...; }' is not assignable to type 'VisualMap'.
                Type '{ type: string; splitNumber: number; min: number; max: number; dimension: number; seriesIndex: number; showLabel: boolean; show: boolean; inRange: { color: string[]; symbolSize: number[]; }; outOfRange: { ...; }; }' is not assignable to type 'VisualMap'.
                  Type '{ type: string; splitNumber: number; min: number; max: number; dimension: number; seriesIndex: number; showLabel: boolean; show: boolean; inRange: { color: string[]; symbolSize: number[]; }; outOfRange: { ...; }; }' is not assignable to type 'Piecewise'.
                    Types of property 'type' are incompatible.
                      Type 'string' is not assignable to type '"piecewise"'.
      Overload 2 of 2, '(props: ReactEchartsCorePropsTypes, context?: any): ReactEchartsCore', gave the following error.
        Type '{ title: {}; visualMap: ({ type: string; splitNumber: number; min: number; max: number; dimension: number; seriesIndex: number; showLabel: boolean; show: boolean; inRange: { color: string[]; symbolSize: number[]; }; outOfRange: { ...; }; } | { ...; })[]; geo: { ...; }; series: ({ ...; } | { ...; })[]; }' is not assignable to type 'EChartOption<Series>'.
    
    ERROR in /root/MusicRadio/frontend/src/layouts/header.tsx
    [tsl] ERROR in /root/MusicRadio/frontend/src/layouts/header.tsx(21,22)
          TS2307: Cannot find module 'config/settings' or its corresponding type declarations.
    
    ERROR in /root/MusicRadio/frontend/src/layouts/index.tsx
    [tsl] ERROR in /root/MusicRadio/frontend/src/layouts/index.tsx(13,22)
          TS2307: Cannot find module 'config/settings' or its corresponding type declarations.
    
    ERROR in /root/MusicRadio/frontend/src/services/socket.ts
    ./src/services/socket.ts
    [tsl] ERROR in /root/MusicRadio/frontend/src/services/socket.ts(4,22)
          TS2307: Cannot find module 'config/settings' or its corresponding type declarations.
null
build failed
Error: build failed
    at /root/MusicRadio/frontend/node_modules/@umijs/bundler-webpack/lib/index.js:108:27
    at finalCallback (/root/MusicRadio/frontend/node_modules/webpack/lib/MultiCompiler.js:254:12)
    at /root/MusicRadio/frontend/node_modules/webpack/lib/MultiCompiler.js:277:6
    at done (/root/MusicRadio/frontend/node_modules/neo-async/async.js:2931:13)
    at runCompilers (/root/MusicRadio/frontend/node_modules/webpack/lib/MultiCompiler.js:181:48)
    at /root/MusicRadio/frontend/node_modules/webpack/lib/MultiCompiler.js:188:7
    at /root/MusicRadio/frontend/node_modules/webpack/lib/MultiCompiler.js:270:7
    at finalCallback (/root/MusicRadio/frontend/node_modules/webpack/lib/Compiler.js:257:39)
    at /root/MusicRadio/frontend/node_modules/webpack/lib/Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/root/MusicRadio/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:40:1)
    at AsyncSeriesHook.lazyCompileHook (/root/MusicRadio/frontend/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/root/MusicRadio/frontend/node_modules/webpack/lib/Compiler.js:271:21)
    at /root/MusicRadio/frontend/node_modules/webpack/lib/Compiler.js:681:15
    at eval (eval at create (/root/MusicRadio/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /root/MusicRadio/frontend/node_modules/ts-loader/dist/after-compile.js:36:9
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/root/MusicRadio/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:5:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `umi build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-11T08_38_12_747Z-debug.log
[root@66 frontend]# npm install --save config/settings
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/config/settings.git
npm ERR! 
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-11T09_42_54_052Z-debug.log

**Comment by sanmmm** [comment]
@Johnson-Rod  前端打包的话请先创建 /frontend/config/settings.ts 文件。该文件为配置文件，配置内容请参考 同目录下的settings.template.ts 文件
